CREATE DATABASE IF NOT EXISTS ClothingStore;
USE ClothingStore;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS tblOrderItem;
DROP TABLE IF EXISTS tblOrder;
DROP TABLE IF EXISTS tblClothes;
DROP TABLE IF EXISTS tblUser;
DROP TABLE IF EXISTS tblAdmin;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS tblAdmin (
    adminID INT AUTO_INCREMENT PRIMARY KEY,
    adminName VARCHAR(100) NOT NULL,
    adminEmail VARCHAR(100) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tblUser (
    userID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    fullName VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    address VARCHAR(255) DEFAULT NULL,
    city VARCHAR(50) DEFAULT NULL,
    zipCode VARCHAR(10) DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    isVerified TINYINT(1) NOT NULL DEFAULT 0,
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tblClothes (
    clothingID INT AUTO_INCREMENT PRIMARY KEY,
    clothingName VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    price DECIMAL(8,2) NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    imageURL VARCHAR(255) DEFAULT NULL,
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tblOrder (
    orderID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    orderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    totalAmount DECIMAL(10,2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    CONSTRAINT fk_order_user FOREIGN KEY (userID) REFERENCES tblUser(userID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tblOrderItem (
    orderItemID INT AUTO_INCREMENT PRIMARY KEY,
    orderID INT NOT NULL,
    clothingID INT NOT NULL,
    quantity INT NOT NULL,
    priceAtPurchase DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_orderitem_order FOREIGN KEY (orderID) REFERENCES tblOrder(orderID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_orderitem_clothing FOREIGN KEY (clothingID) REFERENCES tblClothes(clothingID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;